tools:
    external_code_coverage: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths:
        - 'config/*'
        - 'node_modules/*'
        - 'public/*'
        - 'reports/*'
        - 'tests/*'
        - 'vendor/*'