<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Hampton Roads PHP User Group'))
            ->setSeparator(' - ')->setAutoEscape(false);
        ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/hrphp/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/hrphp/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/vendor/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/vendor/bootstrap/dist/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/vendor/bootstrap/dist/css/bootstrap.min.css'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/vendor/jquery/dist/jquery.min.js')
            ->prependFile($this->basePath() . '/assets/vendor/respond/dest/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/assets/vendor/html5shiv/dist/html5shiv.min.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body>
    <a href="https://github.com/hrphp/portal"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>
        <!--
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand brand" href="<?php echo $this->url('home'); ?>">
                        <?php echo sprintf($this->translate('hr%sphp%s'), '<span class="hrphp-logo-alt">', '</span>'); ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Home'); ?></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        -->
        <div class="container">
            <?php echo $this->content; ?>
            <footer>
                <div class="social-icons">
                    <a href="http://github.com/hrphp" title="hrphp on GitHub" class="social"><i class="fa fa-github"></i></a>
                    <a href="http://757dev.org" title="757Dev Slack" class="social"><i class="fa fa-slack"></i></a>
                    <a href="http://twitter.com/hrphpmeetup" title="hrphp on Twitter" class="social"><i class="fa fa-twitter"></i></a>
                </div>
                <p>&copy; 2013 - <?php echo date('Y'); ?> Hampton Roads PHP User Group. <?php echo $this->translate('All rights reserved.'); ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
