<div class="jumbotron">
    <h1 class="brand">
        <?php echo sprintf($this->translate('hr%sphp%s'), '<span class="hrphp-logo-alt">', '</span>'); ?>
    </h1>
</div>

<div class="row">

    <div class="col-md-12">
        <p class="lead">
            <?php echo $this->translate('The <strong>Hampton Roads PHP User Group</strong> is for PHP developers of all experience levels. We discuss the ways people are using PHP with other technologies, new language features, and whatever else is on our minds.'); ?>
        </p>
        <p>
            <a class="btn btn-lg btn-default" href="http://www.meetup.com/Hampton-Roads-PHP-Meetup/">Learn More</a>
            <a class="btn btn-lg btn-default" href="http://twitter.com/hrphpmeetup">Follow us on Twitter</a>
            <a class="btn btn-lg btn-default" href="http://757dev.org">Follow us on Twitter</a>
        </p>
    </div>

</div>
