<div class="jumbotron">
    <h1 class="brand">
        <?php echo sprintf($this->translate('hr%sphp%s'), '<span class="hrphp-logo-alt">', '</span>'); ?>
    </h1>
</div>

<div class="row">

    <div class="col-md-12">
        <p class="lead">
            <?php echo $this->translate('The <strong>Hampton Roads PHP User Group</strong> is for PHP developers of all experience levels. We discuss the ways people are using PHP with other technologies, new language features, and whatever else is on our minds.'); ?>
        </p>
    </div>
    <div class="meetup service col-lg-3 col-lg-offset-3">
        <div class="media">
            <div class="media-left">
                <a href="http://www.meetup.com/Hampton-Roads-PHP-Meetup" class="social"><i class="fa fa-2x fa-calendar"></i></a>
            </div>
            <div class="media-body" itemprop="event" itemscope itemtype="http://schema.org/Event">
                <p id="event-container">
                    <i class="fa fa-spin fa-circle-o-notch"></i>
                </p>
            </div>
        </div>
    </div>
    <div class="twitter service col-lg-3">
        <div class="media">
            <div class="media-left">
                <a href="https://twitter.com/hrphpmeetup" class="social"><i class="fa fa-2x fa-twitter"></i></a>
            </div>
            <div class="media-body">
                <p id="tweet-container">
                    <i class="fa fa-spin fa-circle-o-notch"></i>
                </p>
            </div>
        </div>
    </div>

</div>
